language: python
python:
  - 3.8

cache:
  directories:
    - __pycache__
    - env
script:
  - python3.8 -m unittest discover
after_success:
  - export CODECOV_TOKEN="token"
  - bash <(curl -s https://codecov.io/bash)