version: '2'
services:
  web:
    container_name: ambu-api
    build: .
    environment: 
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:docker@10.0.0.118:5432/postgres"
    ports:
      - "5000:5000"
