version: '2'
services:
  web:
    container_name: ambu-api
    build: .
    environment: 
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      SQLALCHEMY_DATABASE_URI: "0.0.0.0:5432"
    ports:
      - "8080:8080"