"""using new version of db

Revision ID: 007e289b4c1d
Revises: 
Create Date: 2020-07-27 18:31:26.956744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007e289b4c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TimeStart', sa.Float(), nullable=True),
    sa.Column('TimeEnd', sa.Float(), nullable=True),
    sa.Column('Version', sa.Integer(), nullable=True),
    sa.Column('Duration', sa.Float(), nullable=True),
    sa.Column('Length', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Response')
    # ### end Alembic commands ###
