"""empty message

Revision ID: 02619776916e
Revises: 767072ee6882
Create Date: 2020-05-06 18:23:02.277281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02619776916e'
down_revision = '767072ee6882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Path', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Path', sa.Integer(), nullable=True),
    sa.Column('TimeStart', sa.Float(), nullable=True),
    sa.Column('TimeEnd', sa.Float(), nullable=True),
    sa.Column('Version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RoadSegment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('From', sa.Integer(), nullable=True),
    sa.Column('To', sa.Float(), nullable=True),
    sa.Column('Frequency', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Simulation_Start', sa.Float(), nullable=True),
    sa.Column('Simulation_End', sa.Float(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Simulation')
    op.drop_table('RoadSegment')
    op.drop_table('Response')
    op.drop_table('Path')
    # ### end Alembic commands ###
