"""empty message

Revision ID: 057d120633b3
Revises: 2c18e1456f04
Create Date: 2020-03-29 18:45:33.699016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '057d120633b3'
down_revision = '2c18e1456f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Simulation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Simulation',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Simulation_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Simulation_Start', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Simulation_End', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Simulation_pkey')
    )
    # ### end Alembic commands ###
