"""empty message

Revision ID: 21529ecfacb7
Revises: 
Create Date: 2020-08-03 12:00:43.070478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21529ecfacb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Heatpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Path',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Path_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Path', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Path_pkey')
    )
    op.drop_table('Heatpoint')
    # ### end Alembic commands ###
