"""empty message

Revision ID: 2c18e1456f04
Revises: b30f162dd7fd
Create Date: 2020-03-29 18:33:18.058523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c18e1456f04'
down_revision = 'b30f162dd7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Simulation_Start', sa.Float(), nullable=True),
    sa.Column('Simulation_End', sa.Float(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Simulation')
    # ### end Alembic commands ###
