"""empty message

Revision ID: 2f3aa2a8b1aa
Revises: 8761560c9c2d
Create Date: 2020-11-19 20:53:39.193676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3aa2a8b1aa'
down_revision = '8761560c9c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Depot', sa.Column('localID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Depot', 'localID')
    # ### end Alembic commands ###
