"""empty message

Revision ID: 3e24a7120a84
Revises: 007e289b4c1d
Create Date: 2020-07-29 15:18:42.769192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e24a7120a84'
down_revision = '007e289b4c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Path', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RoadSegment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('From', sa.Integer(), nullable=True),
    sa.Column('To', sa.Float(), nullable=True),
    sa.Column('Frequency', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Simulation_Start', sa.Float(), nullable=True),
    sa.Column('Simulation_End', sa.Float(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Simulation')
    op.drop_table('RoadSegment')
    op.drop_table('Path')
    # ### end Alembic commands ###
