"""Initial migration.

Revision ID: 4a58f0ad6795
Revises: 
Create Date: 2020-10-06 15:56:38.429968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a58f0ad6795'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Heatpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TimeStart', sa.Float(), nullable=True),
    sa.Column('TimeEnd', sa.Float(), nullable=True),
    sa.Column('Version', sa.Integer(), nullable=True),
    sa.Column('Duration', sa.Float(), nullable=True),
    sa.Column('Length', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RoadSegment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('From', sa.Integer(), nullable=True),
    sa.Column('To', sa.Float(), nullable=True),
    sa.Column('Frequency', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Simulation_Start', sa.Float(), nullable=True),
    sa.Column('Simulation_End', sa.Float(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Simulation')
    op.drop_table('RoadSegment')
    op.drop_table('Response')
    op.drop_table('Heatpoint')
    # ### end Alembic commands ###
