"""empty message

Revision ID: 4d9c90a9db2b
Revises: 
Create Date: 2020-05-10 11:53:45.144256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9c90a9db2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Path', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Path', sa.Integer(), nullable=True),
    sa.Column('TimeStart', sa.Float(), nullable=True),
    sa.Column('TimeEnd', sa.Float(), nullable=True),
    sa.Column('Version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RoadSegment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('From', sa.Integer(), nullable=True),
    sa.Column('To', sa.Float(), nullable=True),
    sa.Column('Frequency', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Simulation_Start', sa.Float(), nullable=True),
    sa.Column('Simulation_End', sa.Float(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Simulation')
    op.drop_table('RoadSegment')
    op.drop_table('Response')
    op.drop_table('Path')
    # ### end Alembic commands ###
