"""empty message

Revision ID: 4ef47fa7f137
Revises: 057d120633b3
Create Date: 2020-03-31 18:45:50.093837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef47fa7f137'
down_revision = '057d120633b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Simulation_Start', sa.Float(), nullable=True),
    sa.Column('Simulation_End', sa.Float(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Simulation')
    # ### end Alembic commands ###
