"""empty message

Revision ID: 8761560c9c2d
Revises: 4a58f0ad6795
Create Date: 2020-11-15 15:36:54.813240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8761560c9c2d'
down_revision = '4a58f0ad6795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Depot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('ambulances', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Optimization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.Column('Response_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('RoadSegment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoadSegment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"RoadSegment_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('From', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('To', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Frequency', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='RoadSegment_pkey')
    )
    op.drop_table('Optimization')
    op.drop_table('Depot')
    # ### end Alembic commands ###
