"""addded path table

Revision ID: bd6e94d52361
Revises: 3c78a1f327fe
Create Date: 2020-04-16 17:16:07.574966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6e94d52361'
down_revision = '3c78a1f327fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Path', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Path')
    # ### end Alembic commands ###
