"""empty message

Revision ID: 3c78a1f327fe
Revises: 
Create Date: 2020-04-16 17:15:09.223107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c78a1f327fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Simulation_Start', sa.Integer(), nullable=True),
    sa.Column('Simulation_End', sa.Float(), nullable=True),
    sa.Column('Year', sa.Float(), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Response')
    # ### end Alembic commands ###
